import { Toaster } from 'react-hot-toast'
import './globals.css'
import { Inter } from 'next/font/google'
import { GlobalState } from '@/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster toastOptions={{ duration: 3000 }} />
      <GlobalState>
      {children}
      </GlobalState>
        </body>
    </html>
  )
}
